{
 "title": "Java App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({service_name=\"java-app\", level=\"ERROR\"}[1m])"
    },
    {
     "expr": "count_over_time({service_name=\"java-app\", level=\"INFO\"}[1m])"
    }
   ]
  },
  {
   "title": "Trace",
   "type": "traces",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "58fd23e5", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "java-app" ],
       "valueType": "string"
      },
      {
       "id": "status",
       "isCustomValue": false,
       "operator": "!=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "ok",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ .service.name = \"java-app\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Error Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"java-app\"} |= \"ERROR\""
    }
   ]
  }
 ]
}